# Generated by Django 3.1.2 on 2020-11-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('state', models.TextField(null=True)),
                ('address1', models.TextField(null=True)),
                ('address2', models.TextField(null=True)),
                ('payment_method', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('username', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=1000)),
                ('token', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('date', models.DateTimeField()),
                ('order_state', models.TextField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('budget', models.FloatField()),
                ('suburb', models.TextField()),
                ('photo', models.BinaryField(null=True)),
                ('video', models.BinaryField(null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Capstone_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('business_name', models.CharField(max_length=30, null=True)),
                ('ABN', models.CharField(max_length=11, null=True)),
                ('ACN', models.CharField(max_length=9, null=True)),
                ('landline_no', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=1000)),
                ('salt', models.CharField(max_length=300, null=True)),
                ('iteration', models.IntegerField(null=True)),
                ('token', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField()),
                ('order_state', models.TextField()),
                ('comment', models.CharField(max_length=100)),
                ('date', models.DateTimeField(null=True)),
                ('EditDate', models.DateTimeField(null=True)),
                ('suburb', models.TextField()),
                ('title', models.TextField()),
                ('category', models.CharField(max_length=30)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Capstone_app.customer')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Capstone_app.order')),
                ('supplier_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Capstone_app.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Capstone_app.supplier'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30, null=True)),
                ('sender', models.CharField(max_length=30, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('content', models.TextField()),
                ('last_conversion', models.BooleanField(null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capstone_app.customer')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capstone_app.supplier')),
            ],
        ),
    ]
